version: '2'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
    labels:
      co.elastic.logs/module: nginx
      co.elastic.logs/fileset.stdout: access
      co.elastic.logs/fileset.stderr: error
    networks:
      - default
      - frontend1
      - frontend2
      - frontend3
      - frontend4
      - frontend5

  dockergen:
    # docker-gen with embedded nginx.tmpl
    image: poma/docker-gen
    container_name: dockergen
    restart: always
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    depends_on:
      - nginx
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    networks:
      - default
      - frontend1
      - frontend2
      - frontend3
      - frontend4
      - frontend5

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    depends_on:
      - nginx
      - dockergen
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
      - frontend1
      - frontend2
      - frontend3
      - frontend4
      - frontend5

volumes:
  conf:
  vhost:
  html:
  certs:

networks:
  default:
  frontend1:
    name: frontend1
  frontend2:
    name: frontend2
  frontend3:
    name: frontend3
  frontend4:
    name: frontend4
  frontend5:
    name: frontend5