#================================ Modules ======================================
filebeat.modules:
  - module: system
    syslog:
      enabled: true
    auth:
      enabled: true
#  - module: auditd
#    log:
#      # Does not look like Auditd is supported in Alpine linux: https://github.com/linuxkit/linuxkit/issues/52
#      enabled: false

#============================== Autodiscover ===================================
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

#=============================== Processors ====================================
processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_locale: ~
  - add_host_metadata:
      netinfo.enabled: true

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}
  username: ${ELASTICSEARCH_USERNAME:elastic}
  password: ${ELASTICSEARCH_PASSWORD:changeme}
  protocol: ${ELASTICSEARCH_PROTOCOL:http}

#============================== Kibana =========================================
setup.kibana:
  host: ${KIBANA_HOST:kibana}:${KIBANA_PORT:5601}
  username: ${ELASTICSEARCH_USERNAME:elastic}
  password: ${ELASTICSEARCH_PASSWORD:changeme}
  protocol: ${ELASTICSEARCH_PROTOCOL:http}

#============================== Dashboards =====================================
setup.dashboards:
  enabled: true
# setup.template.overwrite: true

#============================== Xpack Monitoring ===============================
xpack.monitoring.enabled: true
